- name: Build (no tests)
  run: mvn -q -DskipTests -pl core -am clean install -Dlicense.skip=true -Dcheckstyle.skip -Drat.skip

- name: Run test normally (expect PASS)
  run: mvn -pl core test -Dtest=org.fourthline.cling.test.gena.EventXMLProcessingTest#writeReadRequestPull

- name: Run with NonDex (expect FAIL)
  run: |
    set +e
    mvn -pl core edu.illinois:nondex-maven-plugin:2.1.1:nondex \
      -Dtest=org.fourthline.cling.test.gena.EventXMLProcessingTest#writeReadRequestPull \
      -DnondexRuns=200 -Dsurefire.rerunFailingTestsCount=0 | tee nondex.log
    EC=$?
    [ $EC -ne 0 ] && echo "Expected NonDex failure reproduced." && exit 0
    echo "Unexpected: NonDex passed."; exit 1