name: Confirm Flaky Test (cling)

on:
  workflow_dispatch:
    inputs:
      nondexRuns:
        description: "Number of NonDex runs"
        required: false
        default: "200"

jobs:
  confirm-flaky:
    runs-on: [self-hosted, cling-runner]
    timeout-minutes: 45
    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout cling
        uses: actions/checkout@v4

      - name: Build (no tests)
        run: >
          mvn -q -DskipTests -Dmaven.javadoc.skip=true
          -pl core -am clean install
          -Dlicense.skip=true -Dcheckstyle.skip -Drat.skip

      - name: Run test normally (expect PASS)
        run: mvn -pl core test -Dtest='org.fourthline.cling.test.gena.EventXMLProcessingTest#writeReadRequestPull'

      - name: Run with NonDex (expect FAIL)
        run: |
          set +e
          mvn -pl core edu.illinois:nondex-maven-plugin:2.1.1:nondex \
            -Dtest='org.fourthline.cling.test.gena.EventXMLProcessingTest#writeReadRequestPull' \
            -DnondexRuns='200' \
            -Dsurefire.rerunFailingTestsCount=0 | tee nondex.log
          EC=$?
          echo "NonDex exit code: $EC"
          [ $EC -ne 0 ] && echo "Expected NonDex failure reproduced." && exit 0
          echo "Unexpected: NonDex passed." && exit 1

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cling-nondex-logs
          path: |
            nondex.log
            core/target/surefire-reports